### ISSUE TITLE
Err and Out deleted after completion?

### ISSUE THREAD

**Issue by paguenther** [marinang/SimulationProduction#10]
Is it on purpose that the err and out files are removed for completed jobs? It's sometimes quite useful to have these as well.

**Comment by marinang** [comment]
It is yes, I guess for storage issues.

What I could do is to add an options to keep the logs (preferably by default I guess), as long as the job is in the job collection ( in the jobs container ). 

However I think it has to be removed when the job is removed from the collection, which means when you do

`jobs[...].remove()`

the job is removed from the collection and the log folder will be removed. Sounds like OK ?

**Comment by marinang** [comment]
Solved with https://github.com/marinang/SimulationProduction/commit/5f23899c4eb5bf032b755c547d2af8b32302bb56 !
