### ISSUE TITLE
Old version of decfiles is loaded

### ISSUE THREAD

**Issue by paguenther** [marinang/SimulationProduction#8]
The getevttype method gets a rather old version of the requested decfile. Should the default be the most recent version?

**Comment by marinang** [comment]
Yes but as the DecFiles package is changing quite often, I don't always remember to put the last one as the default.

**Comment by marinang** [comment]
Solved with https://github.com/marinang/SimulationProduction/commit/5f23899c4eb5bf032b755c547d2af8b32302bb56 !
